import React, { createContext, useContext, useState, ReactNode } from 'react';

type Lang = 'BG' | 'EN' | 'RU';

const translations = {
  BG: {
    nav: {
      home: 'Начало',
      services: 'Услуги',
      howItWorks: 'Как работим',
      auctions: 'Търгове',
      offers: 'Предложения',
      whyUs: 'Защо ние',
      testimonials: 'Отзиви',
      faq: 'FAQ',
      contact: 'Контакти',
      cta: 'Безплатна консултация',
      phone: 'Обади се',
    },
    hero: {
      label: '№1 Вносител на автомобили',
      h1a: 'ВАШИЯТ',
      h1b: 'АМЕРИКАНСКИ',
      h1c: 'АВТОМОБИЛ В',
      h1d: 'БЪЛГАРИЯ',
      sub: 'Купуваме директно от търговете в САЩ и Канада. Транспортираме до България и цяла Европа през Ротердам. Организираме всички митнически и регистрационни документи — вие само получавате колата.',
      cta: 'Поръчай автомобил',
      secondary: 'Как работим',
      scrollMore: 'Научете повече',
    },
    stats: {
      delivered: 'Доставени коли',
      delivery: 'Дни доставка',
      transparent: 'Прозрачност',
    },
    howItWorks: {
      label: 'Процесът',
      title: 'Как работи',
      titleAccent: 'стъпка по стъпка',
      sub: 'Прозрачен и опростен процес — ние поемаме всичко сложното, вие само избирате автомобила си.',
      steps: [
        { label: 'Запитване', desc: 'Споделяте изискванията и предпочитанията си.' },
        { label: 'Подбор и оферта', desc: 'Намираме най-добрите опции и ви предоставяме оферта.' },
        { label: 'Изкупуване', desc: 'Изкупуваме автомобила на най-добра цена.' },
        { label: 'Доставка', desc: 'Транспортираме автомобила до България.' },
        { label: 'Митница и доставка', desc: 'Митническо оформяне и доставка до вас.' },
      ],
    },
    offers: {
      label: 'Горещи предложения',
      title: 'Актуални коли от',
      titleAccent: 'американските търгове',
      sub: 'Избери директно от наличните предложения или поръчай конкретен модел по заявка.',
      inquire: 'Запитване',
      noOffers: 'Няма активни предложения в момента.',
      comingSoon: 'Очаквайте скоро',
      customOrder: 'Запитване по желание',
    },
    whyUs: {
      label: 'Защо да изберете нас',
      title: 'Не просто внос —',
      titleAccent: 'пълно обслужване',
      sub: 'Занимаваме се изключително с внос на автомобили от Америка. Това е нашата специализация и нашата страст. Знаем всеки детайл от процеса и можем да ви спестим хиляди левове.',
      cta: 'Разговор с експерт',
      stats: [
        { label: 'Внесени автомобила' },
        { label: 'Години на пазара' },
        { label: 'Доволни клиенти' },
        { label: 'По-евтино от България' },
      ],
      reasons: [
        { title: 'Директен достъп до търгове', description: 'Имаме дилърски акаунти на Copart, IAAI и Manheim. Закупуваме без посредници, което означава по-ниска цена за вас.' },
        { title: 'Пълна прозрачност', description: 'Следите всяка стъпка — от наддаването до доставката. Реални снимки, реални документи, никакви изненади.' },
        { title: 'Гарантирана доставка', description: 'Имаме застраховка по целия маршрут. Поемаме отговорност за автомобила ви от момента на покупката.' },
        { title: 'Опитен екип', description: 'Над 10 години опит в автомобилния внос. Познаваме всяка процедура, всеки документ, всяка митница.' },
      ],
    },
    testimonials: {
      label: 'Отзиви',
      title: 'Какво казват',
      titleAccent: 'нашите клиенти',
      avgRating: 'Средна оценка',
      happyClients: 'Доволни клиенти',
    },
    faq: {
      label: 'Въпроси и отговори',
      title: 'Често задавани',
      titleAccent: 'въпроси',
      sub: 'Намерете отговор на най-честите въпроси. Не намирате отговор? Свържете се с нас.',
      items: [
        { q: 'Какви автомобили можете да внесете?', a: 'Внасяме всякакви автомобили — нови, употребявани, с малки щети или тотални отписвания от застрахователи. Специализирани сме в американски марки, но внасяме японски, европейски и всякакви други марки достъпни на американските търгове.' },
        { q: 'Колко струва вносът на автомобил?', a: 'Разходите зависят от цената на автомобила, вида транспорт и митническите такси. Обикновено транспортните и митническите разходи варират между €1500 и €3500. Ние ви даваме пълна калкулация предварително без скрити такси.' },
        { q: 'Колко дълго трае процесът?', a: 'Обикновено от момента на покупка до получаване на автомобила са нужни 6-8 седмици. Товарна кораб до Ротердам — 3-4 седмици, митническо оформяне — 1-2 седмици, транспорт до България — 3-5 дни.' },
        { q: 'Мога ли да следя доставката?', a: 'Да, предоставяме ви проследяващ номер на контейнера. Ще ви информираме на всяка ключова стъпка — покупка, натоварване, отплаване, пристигане в Ротердам, митница, доставка до вас.' },
        { q: 'Какви документи ще получа?', a: 'Получавате американски Title (собственически документ), Bill of Lading (морска товарителница), CMR, митнически декларации и COC сертификат за регистрация в ЕС. Всичко необходимо за регистрация в КАТ.' },
        { q: 'Внасяте ли коли с щети?', a: 'Да, специализираме се именно в коли с щети от Copart и IAAI. Много от тях имат козметични или леки повреди и са изключително изгодни. При желание можем да организираме ремонт след пристигане.' },
        { q: 'Работите ли с европейски клиенти, не само България?', a: 'Да, внасяме автомобили за клиенти из цяла Европа. Ротердам е нашата централна точка и оттам разпределяме за Румъния, Германия, Австрия, Франция и всяка друга страна в ЕС.' },
        { q: 'Как да започна?', a: 'Свържете се с нас по телефон или чрез формата за контакт. Ще ви проведем безплатна консултация, ще обсъдим какво търсите и ще ви дадем точна оферта без ангажимент.' },
      ],
    },
    contact: {
      label: 'Свържете се с нас',
      title: 'Готови ли сте да намерите',
      titleAccent: 'мечтания автомобил?',
      sub: 'Консултацията е напълно безплатна и без ангажимент. Разкажете ни какво търсите и ние ще намерим най-добрата оферта за вас.',
      infoTitle: 'Контактна информация',
      phoneLabel: 'Телефон',
      emailLabel: 'Имейл',
      addressLabel: 'Адрес',
      hoursTitle: 'Работно време',
      hours: [
        { day: 'Понеделник — Петък', hours: '09:00 — 18:00' },
        { day: 'Събота', hours: '10:00 — 15:00' },
        { day: 'Неделя', hours: 'Затворено' },
      ],
      freeEval: 'Безплатна оценка',
      savings: 'Колко ще спестите?',
      formTitle: 'Запитване за автомобил',
      name: 'Вашето име',
      namePlaceholder: 'Иван Иванов',
      phonePlaceholder: '+359 888 ...',
      car: 'Желан автомобил',
      carPlaceholder: 'напр. BMW X5 2020, Ford Mustang...',
      budget: 'Бюджет',
      budgetDefault: 'Изберете бюджет',
      message: 'Допълнителна информация',
      messagePlaceholder: 'Разкажете ни повече за желания автомобил...',
      send: 'Изпрати запитване',
      sending: 'Изпращане...',
      sent: 'Съобщението е изпратено!',
      sentSub: 'Ще се свържем с вас в рамките на 24 часа. Очаквайте обаждане или имейл.',
      newInquiry: 'Изпратете ново запитване',
      footer: 'Консултацията е безплатна. Отговаряме в рамките на 24 часа.',
      error: 'Грешка при изпращане. Моля обадете се директно на телефона.',
    },
    calculator: {
      label: 'Калкулатор',
      title: 'Изчисли',
      titleAccent: 'всички разходи',
      sub: 'Приблизителна сметка за внос от САЩ до вашия гараж в България.',
      priceLabel: 'Цена на аукцион (USD)',
      fuelLabel: 'Вид гориво',
      fuels: [
        { key: 'petrol', label: 'Бензин', emoji: '⛽' },
        { key: 'diesel', label: 'Дизел', emoji: '🛢' },
        { key: 'electric', label: 'Ел.', emoji: '⚡' },
      ],
      savingsText: 'Спестявате приблизително',
      savingsSub: 'спрямо покупка от български дилър',
      totalLabel: 'Общо (прибл.)',
      ctaButton: 'Поискай точна оферта',
      disclaimer: '* Приблизителна сметка. Точната цена зависи от модела, годината и текущите курсове.',
      rows: [
        { label: 'Цена на автомобила', info: 'Конвертирана от USD по текущ курс' },
        { label: 'Аукционна такса', info: 'Стандартна такса на Copart/IAAI' },
        { label: 'Транспорт в САЩ', info: 'От аукциона до пристанището' },
        { label: 'Океански превоз', info: 'САЩ → Ротердам, 20–30 дни' },
        { label: 'Застраховка', info: '~1.5% от стойността на колата' },
        { label: 'Ротердам обработка', info: 'Пристанищни такси, EU документи' },
        { label: 'Митническа такса (6.5%)', info: 'EU тарифа за внос от САЩ' },
        { label: 'Акциз', info: 'Зависи от вида гориво' },
        { label: 'ДДС (20%)', info: 'Върху цялата данъчна основа' },
        { label: 'Такса за услугата', info: 'Организация, документи, доставка' },
      ],
    },
    routeMap: {
      label: 'Маршрут',
      title: 'От търга до',
      titleAccent: 'вашия гараж',
      sub: 'Осигуряваме пълен транспортен коридор от американски пристанища до всяка точка в България и Европа.',
      stops: [
        { city: 'САЩ', sub: 'Copart / IAAI', flag: '🇺🇸' },
        { city: 'Ротердам', sub: 'EU Hub', flag: '🇳🇱' },
        { city: 'България', sub: 'Доставка до вас', flag: '🇧🇬' },
      ],
      timeline: [
        { label: 'Подготовка', days: '7–10 дни' },
        { label: 'Морски транспорт', days: '20–30 дни' },
        { label: 'Митница', days: '5–10 дни' },
        { label: 'Последна доставка', days: '3–5 дни' },
      ],
      durations: ['20–30 дни', '7–14 дни'],
      total: 'Общо:',
      totalDays: '45–60 дни',
      totalSuffix: 'от поръчка до доставка',
    },
    partners: {
      label: 'Доверени партньори',
      title: 'Директен достъп до',
      titleAccent: 'водещите търгове',
    },
    footer: {
      description: 'Специализирани в внос на автомобили от американски и канадски търгове. Доставяме до България и цяла Европа с пълно документално обслужване.',
      services: 'Услуги',
      info: 'Информация',
      contacts: 'Контакти',
      copyright: 'AutoImport BG. Всички права запазени.',
      privacy: 'Политика за поверителност',
      terms: 'Общи условия',
      serviceLinks: ['Търсене и избор', 'Участие в търг', 'Морски транспорт', 'Митническо оформяне', 'Доставка до вкъщи'],
      infoLinks: ['Как работим', 'Горещи предложения', 'Защо ние', 'Отзиви', 'Въпроси и отговори'],
    },
    ctaBanner: {
      badge: 'Безплатна консултация',
      title: 'Готови ли сте да поръчате вашия автомобил?',
      sub: 'Свържете се с нас и получете безплатна оценка в рамките на 24 часа. Без ангажимент.',
      cta: 'Поръчай сега',
    },
  },

  EN: {
    nav: {
      home: 'Home',
      services: 'Services',
      howItWorks: 'How It Works',
      auctions: 'Auctions',
      offers: 'Offers',
      whyUs: 'Why Us',
      testimonials: 'Reviews',
      faq: 'FAQ',
      contact: 'Contact',
      cta: 'Free Consultation',
      phone: 'Call Us',
    },
    hero: {
      label: '#1 Car Importer',
      h1a: 'YOUR',
      h1b: 'AMERICAN',
      h1c: 'CAR IN',
      h1d: 'BULGARIA',
      sub: 'We buy directly from US and Canadian auctions. We ship to Bulgaria and all of Europe via Rotterdam. We handle all customs and registration documents — you just receive the car.',
      cta: 'Order a Car',
      secondary: 'How It Works',
      scrollMore: 'Learn More',
    },
    stats: {
      delivered: 'Cars Delivered',
      delivery: 'Days Delivery',
      transparent: 'Transparency',
    },
    howItWorks: {
      label: 'The Process',
      title: 'How It Works',
      titleAccent: 'Step by Step',
      sub: 'A transparent and simplified process — we handle all the complexity, you just choose your car.',
      steps: [
        { label: 'Inquiry', desc: 'Share your requirements and preferences.' },
        { label: 'Selection & Quote', desc: 'We find the best options and provide a quote.' },
        { label: 'Purchase', desc: 'We purchase the car at the best price.' },
        { label: 'Shipping', desc: 'We transport the car to Bulgaria.' },
        { label: 'Customs & Delivery', desc: 'Customs clearance and delivery to you.' },
      ],
    },
    offers: {
      label: 'Hot Offers',
      title: 'Current cars from',
      titleAccent: 'US auctions',
      sub: 'Choose directly from available listings or order a specific model on request.',
      inquire: 'Inquire',
      noOffers: 'No active offers at the moment.',
      comingSoon: 'Coming Soon',
      customOrder: 'Custom Order',
    },
    whyUs: {
      label: 'Why Choose Us',
      title: 'Not just import —',
      titleAccent: 'full service',
      sub: 'We specialize exclusively in car imports from America. This is our expertise and passion. We know every detail of the process and can save you thousands.',
      cta: 'Talk to an Expert',
      stats: [
        { label: 'Cars Imported' },
        { label: 'Years in Business' },
        { label: 'Happy Clients' },
        { label: 'Cheaper Than Local' },
      ],
      reasons: [
        { title: 'Direct Access to Auctions', description: 'We have dealer accounts at Copart, IAAI and Manheim. We buy without intermediaries, meaning lower prices for you.' },
        { title: 'Full Transparency', description: 'Track every step — from bidding to delivery. Real photos, real documents, no surprises.' },
        { title: 'Guaranteed Delivery', description: 'We have insurance along the entire route. We take responsibility for your car from the moment of purchase.' },
        { title: 'Experienced Team', description: 'Over 10 years in car importing. We know every procedure, every document, every customs office.' },
      ],
    },
    testimonials: {
      label: 'Reviews',
      title: 'What Our',
      titleAccent: 'Clients Say',
      avgRating: 'Average Rating',
      happyClients: 'Happy Clients',
    },
    faq: {
      label: 'FAQ',
      title: 'Frequently Asked',
      titleAccent: 'Questions',
      sub: "Find answers to the most common questions. Can't find what you're looking for? Contact us.",
      items: [
        { q: 'What types of cars can you import?', a: 'We import all types of cars — new, used, lightly damaged, or total loss write-offs. We specialize in American brands but also import Japanese, European and any other brand available at US auctions.' },
        { q: 'How much does car import cost?', a: 'Costs depend on the car price, type of transport, and customs fees. Typically transport and customs costs range between €1,500 and €3,500. We provide a full calculation upfront with no hidden fees.' },
        { q: 'How long does the process take?', a: 'Typically from purchase to receiving your car takes 6–8 weeks. Cargo ship to Rotterdam — 3–4 weeks, customs clearance — 1–2 weeks, transport to Bulgaria — 3–5 days.' },
        { q: 'Can I track the delivery?', a: 'Yes, we provide you with a container tracking number. We will keep you informed at every key step — purchase, loading, departure, arrival in Rotterdam, customs, delivery to you.' },
        { q: 'What documents will I receive?', a: 'You receive the US Title (ownership document), Bill of Lading, CMR, customs declarations, and a COC certificate for EU registration. Everything needed for registration.' },
        { q: 'Do you import damaged cars?', a: 'Yes, we specialize in damaged cars from Copart and IAAI. Many have only cosmetic or minor damage and are excellent value. We can arrange repairs upon arrival if desired.' },
        { q: 'Do you work with European clients outside Bulgaria?', a: 'Yes, we import cars for clients throughout Europe. Rotterdam is our central hub from where we distribute to Romania, Germany, Austria, France and any other EU country.' },
        { q: 'How do I get started?', a: 'Contact us by phone or through the contact form. We will conduct a free consultation, discuss what you are looking for, and give you an exact quote with no obligation.' },
      ],
    },
    contact: {
      label: 'Get in Touch',
      title: 'Ready to find your',
      titleAccent: 'dream car?',
      sub: "Consultation is completely free and without obligation. Tell us what you're looking for and we'll find the best offer for you.",
      infoTitle: 'Contact Information',
      phoneLabel: 'Phone',
      emailLabel: 'Email',
      addressLabel: 'Address',
      hoursTitle: 'Business Hours',
      hours: [
        { day: 'Monday — Friday', hours: '09:00 — 18:00' },
        { day: 'Saturday', hours: '10:00 — 15:00' },
        { day: 'Sunday', hours: 'Closed' },
      ],
      freeEval: 'Free Estimate',
      savings: 'How much will you save?',
      formTitle: 'Car Inquiry',
      name: 'Your Name',
      namePlaceholder: 'John Smith',
      phonePlaceholder: '+1 555 ...',
      car: 'Desired Car',
      carPlaceholder: 'e.g. BMW X5 2020, Ford Mustang...',
      budget: 'Budget',
      budgetDefault: 'Select budget',
      message: 'Additional Information',
      messagePlaceholder: 'Tell us more about the car you want...',
      send: 'Send Inquiry',
      sending: 'Sending...',
      sent: 'Message Sent!',
      sentSub: 'We will get back to you within 24 hours. Expect a call or email.',
      newInquiry: 'Send New Inquiry',
      footer: 'Consultation is free. We respond within 24 hours.',
      error: 'Error sending. Please call us directly.',
    },
    calculator: {
      label: 'Calculator',
      title: 'Calculate',
      titleAccent: 'all costs',
      sub: 'Approximate cost breakdown for importing from the USA to your garage in Bulgaria.',
      priceLabel: 'Auction Price (USD)',
      fuelLabel: 'Fuel Type',
      fuels: [
        { key: 'petrol', label: 'Petrol', emoji: '⛽' },
        { key: 'diesel', label: 'Diesel', emoji: '🛢' },
        { key: 'electric', label: 'Electric', emoji: '⚡' },
      ],
      savingsText: 'You save approximately',
      savingsSub: 'compared to buying from a Bulgarian dealer',
      totalLabel: 'Total (approx.)',
      ctaButton: 'Request Exact Quote',
      disclaimer: '* Approximate estimate. Exact price depends on model, year, and current exchange rates.',
      rows: [
        { label: 'Car Price', info: 'Converted from USD at current rate' },
        { label: 'Auction Fee', info: 'Standard Copart/IAAI fee' },
        { label: 'US Transport', info: 'From auction to port' },
        { label: 'Ocean Freight', info: 'USA → Rotterdam, 20–30 days' },
        { label: 'Insurance', info: '~1.5% of car value' },
        { label: 'Rotterdam Handling', info: 'Port fees, EU documents' },
        { label: 'Import Duty (6.5%)', info: 'EU tariff for US imports' },
        { label: 'Excise Tax', info: 'Depends on fuel type' },
        { label: 'VAT (20%)', info: 'On total tax base' },
        { label: 'Service Fee', info: 'Organisation, documents, delivery' },
      ],
    },
    routeMap: {
      label: 'Route',
      title: 'From auction to',
      titleAccent: 'your garage',
      sub: 'We provide a complete transport corridor from US ports to any point in Bulgaria and Europe.',
      stops: [
        { city: 'USA', sub: 'Copart / IAAI', flag: '🇺🇸' },
        { city: 'Rotterdam', sub: 'EU Hub', flag: '🇳🇱' },
        { city: 'Bulgaria', sub: 'Delivery to you', flag: '🇧🇬' },
      ],
      timeline: [
        { label: 'Preparation', days: '7–10 days' },
        { label: 'Ocean Transport', days: '20–30 days' },
        { label: 'Customs', days: '5–10 days' },
        { label: 'Final Delivery', days: '3–5 days' },
      ],
      durations: ['20–30 days', '7–14 days'],
      total: 'Total:',
      totalDays: '45–60 days',
      totalSuffix: 'from order to delivery',
    },
    partners: {
      label: 'Trusted Partners',
      title: 'Direct Access to',
      titleAccent: 'Leading Auctions',
    },
    footer: {
      description: 'Specialized in importing cars from American and Canadian auctions. We deliver to Bulgaria and all of Europe with full documentation services.',
      services: 'Services',
      info: 'Information',
      contacts: 'Contacts',
      copyright: 'AutoImport BG. All rights reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms & Conditions',
      serviceLinks: ['Search & Selection', 'Auction Participation', 'Ocean Freight', 'Customs Clearance', 'Home Delivery'],
      infoLinks: ['How It Works', 'Hot Offers', 'Why Us', 'Reviews', 'FAQ'],
    },
    ctaBanner: {
      badge: 'Free Consultation',
      title: 'Ready to order your car?',
      sub: 'Contact us and get a free estimate within 24 hours. No obligation.',
      cta: 'Get Started',
    },
  },

  RU: {
    nav: {
      home: 'Главная',
      services: 'Услуги',
      howItWorks: 'Как работаем',
      auctions: 'Аукционы',
      offers: 'Предложения',
      whyUs: 'Почему мы',
      testimonials: 'Отзывы',
      faq: 'FAQ',
      contact: 'Контакты',
      cta: 'Бесплатная консультация',
      phone: 'Позвонить',
    },
    hero: {
      label: '№1 Импортёр автомобилей',
      h1a: 'ВАШ',
      h1b: 'АМЕРИКАНСКИЙ',
      h1c: 'АВТОМОБИЛЬ В',
      h1d: 'БОЛГАРИИ',
      sub: 'Покупаем напрямую с аукционов США и Канады. Доставляем в Болгарию и всю Европу через Роттердам. Организуем все таможенные и регистрационные документы — вы просто получаете автомобиль.',
      cta: 'Заказать автомобиль',
      secondary: 'Как это работает',
      scrollMore: 'Узнать больше',
    },
    stats: {
      delivered: 'Доставленных авто',
      delivery: 'Дней доставка',
      transparent: 'Прозрачность',
    },
    howItWorks: {
      label: 'Процесс',
      title: 'Как это работает',
      titleAccent: 'шаг за шагом',
      sub: 'Прозрачный и упрощённый процесс — мы берём на себя все сложности, вы просто выбираете автомобиль.',
      steps: [
        { label: 'Запрос', desc: 'Вы сообщаете свои требования и предпочтения.' },
        { label: 'Подбор и предложение', desc: 'Мы находим лучшие варианты и предоставляем предложение.' },
        { label: 'Покупка', desc: 'Выкупаем автомобиль по лучшей цене.' },
        { label: 'Доставка', desc: 'Транспортируем автомобиль в Болгарию.' },
        { label: 'Таможня и доставка', desc: 'Таможенное оформление и доставка до вас.' },
      ],
    },
    offers: {
      label: 'Горячие предложения',
      title: 'Актуальные авто с',
      titleAccent: 'американских аукционов',
      sub: 'Выберите прямо из доступных предложений или закажите конкретную модель.',
      inquire: 'Запрос',
      noOffers: 'Нет активных предложений.',
      comingSoon: 'Скоро',
      customOrder: 'Запрос по желанию',
    },
    whyUs: {
      label: 'Почему мы',
      title: 'Не просто импорт —',
      titleAccent: 'полное обслуживание',
      sub: 'Мы занимаемся исключительно импортом автомобилей из Америки. Это наша специализация и страсть. Мы знаем каждую деталь процесса и можем сэкономить вам тысячи.',
      cta: 'Поговорить с экспертом',
      stats: [
        { label: 'Импортировано авто' },
        { label: 'Лет на рынке' },
        { label: 'Довольных клиентов' },
        { label: 'Дешевле местных цен' },
      ],
      reasons: [
        { title: 'Прямой доступ к аукционам', description: 'У нас есть дилерские аккаунты на Copart, IAAI и Manheim. Покупаем без посредников — это означает более низкую цену для вас.' },
        { title: 'Полная прозрачность', description: 'Отслеживайте каждый шаг — от торгов до доставки. Реальные фото, реальные документы, никаких сюрпризов.' },
        { title: 'Гарантированная доставка', description: 'У нас есть страховка на всём маршруте. Берём ответственность за ваш автомобиль с момента покупки.' },
        { title: 'Опытная команда', description: 'Более 10 лет в сфере импорта автомобилей. Знаем каждую процедуру, каждый документ, каждую таможню.' },
      ],
    },
    testimonials: {
      label: 'Отзывы',
      title: 'Что говорят',
      titleAccent: 'наши клиенты',
      avgRating: 'Средняя оценка',
      happyClients: 'Довольных клиентов',
    },
    faq: {
      label: 'Вопросы и ответы',
      title: 'Часто задаваемые',
      titleAccent: 'вопросы',
      sub: 'Найдите ответы на наиболее частые вопросы. Не нашли ответ? Свяжитесь с нами.',
      items: [
        { q: 'Какие автомобили вы можете импортировать?', a: 'Мы импортируем любые автомобили — новые, б/у, с небольшими повреждениями или тотальными убытками. Специализируемся на американских марках, но также ввозим японские, европейские и любые другие марки с американских аукционов.' },
        { q: 'Сколько стоит импорт автомобиля?', a: 'Расходы зависят от стоимости автомобиля, вида транспортировки и таможенных сборов. Обычно транспортные и таможенные расходы составляют от €1 500 до €3 500. Мы предоставляем полный расчёт заранее без скрытых платежей.' },
        { q: 'Сколько занимает весь процесс?', a: 'Обычно от момента покупки до получения автомобиля требуется 6–8 недель. Грузовое судно до Роттердама — 3–4 недели, таможенное оформление — 1–2 недели, транспорт до Болгарии — 3–5 дней.' },
        { q: 'Могу ли я отслеживать доставку?', a: 'Да, мы предоставляем трекинг-номер контейнера. Вы будете информированы о каждом ключевом шаге — покупка, погрузка, отправление, прибытие в Роттердам, таможня, доставка до вас.' },
        { q: 'Какие документы я получу?', a: 'Вы получаете американский Title (документ о праве собственности), Bill of Lading, CMR, таможенные декларации и сертификат COC для регистрации в ЕС. Всё необходимое для регистрации.' },
        { q: 'Вы ввозите повреждённые автомобили?', a: 'Да, мы специализируемся на автомобилях с повреждениями от Copart и IAAI. Многие из них имеют лишь косметические повреждения и являются очень выгодными. При желании можем организовать ремонт после прибытия.' },
        { q: 'Работаете ли вы с клиентами по всей Европе?', a: 'Да, мы импортируем автомобили для клиентов по всей Европе. Роттердам — наш центральный хаб, откуда мы доставляем в Румынию, Германию, Австрию, Францию и любую другую страну ЕС.' },
        { q: 'Как начать?', a: 'Свяжитесь с нами по телефону или через форму обратной связи. Мы проведём бесплатную консультацию, обсудим, что вы ищете, и дадим точное предложение без каких-либо обязательств.' },
      ],
    },
    contact: {
      label: 'Свяжитесь с нами',
      title: 'Готовы найти свой',
      titleAccent: 'автомобиль мечты?',
      sub: 'Консультация абсолютно бесплатна и ни к чему не обязывает. Расскажите нам, что вы ищете, и мы найдём лучшее предложение.',
      infoTitle: 'Контактная информация',
      phoneLabel: 'Телефон',
      emailLabel: 'Email',
      addressLabel: 'Адрес',
      hoursTitle: 'Рабочие часы',
      hours: [
        { day: 'Понедельник — Пятница', hours: '09:00 — 18:00' },
        { day: 'Суббота', hours: '10:00 — 15:00' },
        { day: 'Воскресенье', hours: 'Закрыто' },
      ],
      freeEval: 'Бесплатная оценка',
      savings: 'Сколько вы сэкономите?',
      formTitle: 'Запрос на автомобиль',
      name: 'Ваше имя',
      namePlaceholder: 'Иван Иванов',
      phonePlaceholder: '+7 999 ...',
      car: 'Желаемый автомобиль',
      carPlaceholder: 'напр. BMW X5 2020, Ford Mustang...',
      budget: 'Бюджет',
      budgetDefault: 'Выберите бюджет',
      message: 'Дополнительная информация',
      messagePlaceholder: 'Расскажите нам подробнее о желаемом автомобиле...',
      send: 'Отправить запрос',
      sending: 'Отправка...',
      sent: 'Сообщение отправлено!',
      sentSub: 'Мы свяжемся с вами в течение 24 часов. Ожидайте звонок или письмо.',
      newInquiry: 'Отправить новый запрос',
      footer: 'Консультация бесплатна. Отвечаем в течение 24 часов.',
      error: 'Ошибка при отправке. Пожалуйста, позвоните нам напрямую.',
    },
    calculator: {
      label: 'Калькулятор',
      title: 'Рассчитайте',
      titleAccent: 'все расходы',
      sub: 'Приблизительный расчёт стоимости импорта из США до вашего гаража в Болгарии.',
      priceLabel: 'Цена на аукционе (USD)',
      fuelLabel: 'Тип топлива',
      fuels: [
        { key: 'petrol', label: 'Бензин', emoji: '⛽' },
        { key: 'diesel', label: 'Дизель', emoji: '🛢' },
        { key: 'electric', label: 'Электро', emoji: '⚡' },
      ],
      savingsText: 'Вы экономите примерно',
      savingsSub: 'по сравнению с покупкой у болгарского дилера',
      totalLabel: 'Итого (прибл.)',
      ctaButton: 'Запросить точное предложение',
      disclaimer: '* Приблизительный расчёт. Точная цена зависит от модели, года и текущих курсов валют.',
      rows: [
        { label: 'Стоимость автомобиля', info: 'Конвертировано из USD по текущему курсу' },
        { label: 'Аукционный сбор', info: 'Стандартный сбор Copart/IAAI' },
        { label: 'Транспорт в США', info: 'От аукциона до порта' },
        { label: 'Морской фрахт', info: 'США → Роттердам, 20–30 дней' },
        { label: 'Страховка', info: '~1.5% от стоимости автомобиля' },
        { label: 'Обработка в Роттердаме', info: 'Портовые сборы, документы ЕС' },
        { label: 'Таможенная пошлина (6.5%)', info: 'Тариф ЕС на импорт из США' },
        { label: 'Акциз', info: 'Зависит от типа топлива' },
        { label: 'НДС (20%)', info: 'На всю налоговую базу' },
        { label: 'Сервисный сбор', info: 'Организация, документы, доставка' },
      ],
    },
    routeMap: {
      label: 'Маршрут',
      title: 'От аукциона до',
      titleAccent: 'вашего гаража',
      sub: 'Обеспечиваем полный транспортный коридор от американских портов до любой точки Болгарии и Европы.',
      stops: [
        { city: 'США', sub: 'Copart / IAAI', flag: '🇺🇸' },
        { city: 'Роттердам', sub: 'Хаб ЕС', flag: '🇳🇱' },
        { city: 'Болгария', sub: 'Доставка до вас', flag: '🇧🇬' },
      ],
      timeline: [
        { label: 'Подготовка', days: '7–10 дней' },
        { label: 'Морская перевозка', days: '20–30 дней' },
        { label: 'Таможня', days: '5–10 дней' },
        { label: 'Финальная доставка', days: '3–5 дней' },
      ],
      durations: ['20–30 дней', '7–14 дней'],
      total: 'Итого:',
      totalDays: '45–60 дней',
      totalSuffix: 'от заказа до доставки',
    },
    partners: {
      label: 'Проверенные партнёры',
      title: 'Прямой доступ к',
      titleAccent: 'ведущим аукционам',
    },
    footer: {
      description: 'Специализируемся на импорте автомобилей с американских и канадских аукционов. Доставляем в Болгарию и всю Европу с полным документальным обслуживанием.',
      services: 'Услуги',
      info: 'Информация',
      contacts: 'Контакты',
      copyright: 'AutoImport BG. Все права защищены.',
      privacy: 'Политика конфиденциальности',
      terms: 'Условия использования',
      serviceLinks: ['Поиск и подбор', 'Участие в аукционе', 'Морская перевозка', 'Таможенное оформление', 'Доставка на дом'],
      infoLinks: ['Как работаем', 'Горячие предложения', 'Почему мы', 'Отзывы', 'Вопросы и ответы'],
    },
    ctaBanner: {
      badge: 'Бесплатная консультация',
      title: 'Готовы заказать свой автомобиль?',
      sub: 'Свяжитесь с нами и получите бесплатную оценку в течение 24 часов. Без обязательств.',
      cta: 'Начать сейчас',
    },
  },
};

const LangContext = createContext<{
  lang: Lang;
  setLang: (l: Lang) => void;
  t: typeof translations['BG'];
}>({
  lang: 'BG',
  setLang: () => {},
  t: translations['BG'],
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>('BG');
  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}

export function useLang() {
  return useContext(LangContext);
}
